#!/bin/bash
#
# wm independent hotkeys
#

#alt + v
#    CM_LAUNCHER=rofi clipmenu \
#        -location 1 \
#        -m -3 \
#        -no-show-icons \
#		-theme fox

super + z
eww open --toggle bar	
# Help 
super + h
	~/.config/rofi/help.sh	
# Terminal Emulator
super + Return
	alacritty
# Calculator 
super + C
	rofi -show calc -modi calc -theme fox -no-show-match -no-sortcalc-command "echo -n '{result}' | xclip"
# Program Launcher
super + @space
	rofi -show combi -theme fox
# Make Sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd; notify-send 'sxhkd' 'Reloaded configs :D'
# Launch Firefox
super + b
	firefox
# Launch NeoVim
super + e
	alacritty -e /bin/neovim
# File Manager 
super + F
	pcmanfm
# Screenshot
super + shift + s
	flameshot gui
# Colour Picker
super + 0
	colorpicker --one-shot --preview --short | xsel -b
#brightness control
XF86MonBrightness{Up,Down}
	brightnessctl s 10%{+,-}
# Lower Volume
XF86AudioLowerVolume
	amixer set Master 5%- 
# Raise Volume
XF86AudioRaiseVolume
	amixer set Master 5%+
# Mute
XF86AudioMute
        amixer set Master toggle
# Play/Pause Spotify
super + alt + b
	playerctl play-pause
# Play Previous Spotify Song
super + alt + v
	playerctl previous
# Play Next Spotify Song
super + alt + n
	playerctl next
# Toggle polybar

#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close focused window
super + q
	bspc node -c
# Change window layout ( floating, tiled, fullscreen ) 
super + Tab
  bspc node -t {floating,tiled,fullscreen}
# Set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen;xdo lower -N eww-bar}
# Set the node flags ( marked, locked, sticky, private )
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# Window Management
#

# Focus the window in the given direction
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}
# Focus the next/previous window in the current desktop
alt + Tab
  bspc node -f next.local.!hidden.window
# Focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local
# Focus monitor 
super + {_, shift +}{comma,period}
	bspc {monitor -f, node -m} {prev,next}
# Focus or send to the given desktop
super + {_,shift + }{1-6}
	bspc {desktop -f,node -d} '^{1-6}'
#
# move/resize
#

# expand a window by moving one of its side outward
# move a floating window
#super + {Left,Down,Up,Right}
#	bspc node -v {-20 0,0 20,0 -20,20 0}

# Resize window
super + alt + {Up,Down,Left,Right}
  {bspc node -z top 10 10; bspc node -z bottom -10 -10, bspc node -z bottom 10 10; bspc node -z top -10 -10, bspc node -z left 10 10; bspc node -z right -10 -10, bspc node -z right 10 10; bspc node -z left -10 -10 }

# Move window to the left/right / up/down
super + shift + {Up,Down,Left,Right}
  bspc node -s {north,south,west,east}
