#! /bin/sh
#github.com/derpyzza
pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI-2 connected') ]]; then
	xrandr --output HDMI-2 --primary --mode 1920x1080 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal --right-of HDMI1
fi

bspc monitor -d 1 2 3 4 5 6

bspc set wm_name LG3D

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config single_monocle true

bspc config border-width	7
bspc config window_gap 		5
bspc config normal_border_color '#-1C1115'
bspc config focused_border_color '#B57EF2'

bspc config split_ration 	-1.52
bspc config borderless_monocle  true
# bspc config gapless_monocle	true
bspc config focus_follows_pointer true
bspc config -m eDP-1 top_padding 0

bspc rule -a mplayer1 	state=floating
bspc rule -a nm-connections-manager state=floating
bspc rule -a kupfer.py focus=on
bspc rule -a ScreenKey manage=off
bspc rule -a "*:Toolkit:Picture-in-Picture" \
     state=floating sticky=on follow=off focus=on \
     rectangle=640x360+1270+710

# Auto Start------------------------------------------------------------------------------

# couple trackpad settings 
xinput set-prop "DELL081C:00 044E:121F Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "DELL081C:00 044E:121F Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DELL081C:00 044E:121F Touchpad" "libinput Disable While Typing Enabled" 0

~/monitors.sh &
# pkill polybar;    polybar -r bar &
eww open bar
#~/bat.sh &
pkill nitrogen;   nitrogen --restore &
pkill picom;      picom --experimental-backends &
pkill nm-applet;  nm-applet &
pkill dunst;      dunst &
# send welcome message :)
xfce4-power-manager &
setxkbmap -option "ctrl:nocaps"
setxkbmap -option "compose:rctrl"
notify-send 'Welcome!' 'press super + h for keybinds :) \n <i>(super is the windows key)</i>'
bluetoothctl scan on &

#------------------------------------------------------------------------------------------
