import = ["/home/derpyzza/.config/alacritty/nyoomfox.toml"]

[cursor.font.bold]
family = "JetBrainsMono"
style = "Extra Bold"

[cursor.font.italic]
family = "JetBrainsMono"
style = "Italic"

[cursor.font.normal]
family = "JetBrainsMono"
style = "Bold"
weight = 700

[cursor.style]
shape = "block"

[window.dimensions]
columns = 70
lines = 25

[window.padding]
x = 40
y = 40
