theme = "mytheme"

[editor]
line-number = "relative"
auto-completion = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
center = ["version-control"]
right = ["diagnostics", "selections", "register", "position", "total-line-numbers", "file-encoding", "file-type"]

[editor.smart-tab]
enable = false

# [editor.lsp]
# display-inlay-hints = true

[editor.indent-guides]
render = true

[keys.normal]
";" = "command_mode"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."space"]
"space" = "file_picker"
s = ":hsplit"
m = ":hsplit-new"
v = ":vsplit"
n = ":vsplit-new"
c = "toggle_comments"
x = "toggle_block_comments"
